name: Validate with hassfest

on:
  workflow_run:
    workflows:
      - Code-checker
    types:
      - completed
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
